### PR TITLE
Windows support!

### PR DESCRIPTION
**Pull request by mustafa-archived**
pog

if u get an error running the code on linux tell me, it'd likely be a deps issue

### CODE REVIEW

**Comment by mustafa-archived** [comment]
see [the files tab](https://github.com/LinuxForGeeks/Silaty/pull/6/files) to see all changes done, the commits page is just for the commits done since I made the repo

**Comment by mustafa-archived** [comment]
oh btw grab the windows release form the repo

**Comment by AXeL-dev** [comment]
Alright! Thank you for the PR, i'll have a deep look on it & test it on both Windows & Linux before merging it.

**Comment by mustafa-archived** [comment]
yeah I have to as well, I've noticed there might be some bugs

**Comment by mustafa-archived** [comment]
Aight, I've fixed a bug where qt doesn't load theme on startup by delaying app startup by 15 sec (some pc's r slow yk idk)

also the notification when prayer wasn't being sent due to icon path being incorrect, fixed that now

I also needed to use a fresh arch installation bc I messed up the startup thing for silaty

lastly maybe In the future I'll update the notification to use qt as well since I noticed notification name is notify.py and not 'Silaty'

**Comment by mustafa-archived** [comment]
also another thing, I'm not rly sure if audio works, silaty generally (old version and this one using same audio code) didn't play an audio on prayertime except once, I might check that later

**Comment by mustafa-archived** [comment]
> Aight, I've fixed a bug where qt doesn't load theme on startup by delaying app startup by 15 sec (some pc's r slow yk idk)

Fixed that in a better way, changed pyside2 to pyqt5 (no need for startup delay anymore), apparently pyside2 doesn't work correctly with themes

**Comment by AXeL-dev** [comment]
@MustafaKhalaf69 Sorry but i didn't find enough time to fully check your PR :pray: , i'll do it once i'm enough free.

**Comment by mustafa-archived** [comment]
Alright

**Comment by mustafa-archived** [comment]
Updates?

**Comment by AXeL-dev** [comment]
> Updates?

Hey, i apologize for the review latency but i was on a vacation lately.

So after a quick code review, i think that replacing GTK app indicator with Qt & keep using both UI libraries isn't a wise move, i better suggest to fully port the app to Qt (which may take a significant time) or keep it on GTK (that's just a geeky perfectionnist guy point of view, i know that the GTK app indicator didn't work well for you on windows).

So for now, i would create a separate branch for the windows version & merge your changes on it, then add a link to it on the master branch, so people can know that there is a windows version available out there. And if ever you're interested, i'll need your help on maintaining the windows branch.

Finally, thank you for your contribution & the great work you did on porting the app to windows! :tada:

**Comment by mustafa-archived** [comment]
Thanks

**Comment by mustafa-archived** [comment]
>  better suggest to fully port the app to Qt

Maybe I'll do it sometime

**Comment by mustafa-archived** [comment]
Remaking with Qt and C++ :)
image

**Comment by mustafa-archived** [comment]
published the code so far https://github.com/mustafakhalaf-git/SilatyQt

whenever this is done I might submit it to this org I guess

**Comment by mustafa-archived** [comment]
so far (I rewrote it to make code better)
image
image

**Comment by mustafa-archived** [comment]
So far I've finished the main stuff (prayer time, notification, audio, etc..) 

The tiny stuff like daylight and that not yet as well as compass but yeah it's pretty much complete

**Comment by mustafakhalaf-git** [comment]
Can you send me a request to join the org so I can move the repo in?

**Comment by mustafa-archived** [comment]
@AXeL-dev Can you send me a request to join the org so I can move the repo in?

**Comment by AXeL-dev** [comment]
Sure!

**Comment by mustafa-archived** [comment]
tysm

**Pull request merged**
