### PR TITLE
ValueError: Namespace Notify not available for version 0.7

### PR DESCRIPTION
**Pull request by mustafa-archived**
I'm using archlinux (idk for other distros) I recently did 'pacman -Syu' to update all packages and got this error

modifying 'Notify' from 0.7 to 0.8 fixed the issue

### CODE REVIEW

**Comment by mustafa-archived** [comment]
I compiled silaty from code to be clear

**Comment by AXeL-dev** [comment]
LGTM, thank you for the PR!

**Comment by mustafa-archived** [comment]
Thanks brother

**Comment by AXeL-dev** [comment]
@MustafaKhalaf69 Did you use the following command to install packages on arch linux?

```
pacman -Syu gir1.2-gtk-3.0 gir1.2-appindicator3-0.1 gir1.2-notify-0.7 gir1.2-gstreamer-1.0
```

perhaps the packages names are a bit different on arch?

**Comment by mustafa-archived** [comment]
Sorry for the delay

Ubuntu repos are different from the AUR, I did this command to install stuff `pacman -Syu gtk3 libappindicator-gtk3 libnotify gstreamer` (not sure about gstreamer)

Ubuntu repos can be often outdated, arch's repos are quickly updated, for the first 2 days of using silaty everything was fine but then I updated all packages with `pacman -Syu` and it seems gstreamer updated from 0.7 to 0.8, searching the bug the fix was to change 0.7 to 0.8

I don't know if ubuntu isers will be outdated or not, if they use pip to install stuff maybe not idk

**Comment by AXeL-dev** [comment]
No worries,

Yeah you're totally right, arch gets always the latest packages updates while it take really a long time for ubuntu to do so.

I think using pip would be a good solution on ubuntu, still for the debian package i'm not sure if that won't be an issue.

Anyway, thank you for the details, i'll add the arch linux packages install command to the README file.

**Comment by mustafa-archived** [comment]
👍

**Comment by mustafa-archived** [comment]
btw just thought I'd share, my friend was interested in a windows version so I ported it with msys2 
image

**Comment by mustafa-archived** [comment]
image

**Comment by mustafa-archived** [comment]
Had to swap linux-only libraries with plyer and wxPython

**Comment by AXeL-dev** [comment]
@MustafaKhalaf69 that's amazing! can you create a PR for that?

**Comment by mustafa-archived** [comment]
I'll see what I can do, not so good at python so idk how I'll make it work in one code file, for now you can find the code in my profile

**Comment by AXeL-dev** [comment]
Alright, no worries!

**Comment by mustafa-archived** [comment]
Hey!, Currently working on the windows pr

My friend sent me this in dm, i thought it was funny so i wanted to share

https://github.com/ali-sameh-galal/Silaty-Mockups

**Comment by AXeL-dev** [comment]
Alright thank you!

The mockups looks great btw :clap:

**Comment by mustafa-archived** [comment]
lol ye, someone made them not me

still making the windows thing, it just takes a little bit time to change linux only libs, I should as well add some docs and stuff in the readme to help more

**Comment by AXeL-dev** [comment]
yeah sure no worries, take your time!

 & yes i noticed that someone else made the mockups, still they really look great!

**Comment by mustafa-archived** [comment]
aight, so far finished all the porting, I changed tray icon to qt library and notifications to notify.py

I wasn't able to get sounds working *yet* so I made them linux only, the work left would be to add some docs and stuff and compile a release etc..

**Comment by mustafa-archived** [comment]
repo *seems* pretty finished, trying to build an executable

**Comment by mustafa-archived** [comment]
alright here's the bug, when using --onefile the exe doesnt rly work correctly

so for now I'll provide a zip of the compiled binary without '--onefile'

**Pull request merged**
